# Generated by Django 3.1.6 on 2021-02-14 10:49

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(default='', max_length=100)),
            preserve_default=False,
        ),
    ]
